package projet.depta.entities;

public enum TypeOption {
    NBDIGITS,NBLIGNES,LISTEPOINTSQOUVERTE,LISTENOMSQOUVERTE,BAREME,POINTS,DECIMAUX,BONNEREPONSE,SIGNE,PTSMAUVAISEREPONSE,COEFFICIENTMAUVAISEREPONSE;
}
